# Generated by Django 5.0.1 on 2025-10-24 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pass',
            name='from_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_given', to='api.pet'),
        ),
        migrations.AddField(
            model_name='pass',
            name='to_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_received', to='api.pet'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.pet'),
        ),
        migrations.AddField(
            model_name='match',
            name='pet1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet1', to='api.pet'),
        ),
        migrations.AddField(
            model_name='match',
            name='pet2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet2', to='api.pet'),
        ),
        migrations.AddField(
            model_name='like',
            name='from_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='api.pet'),
        ),
        migrations.AddField(
            model_name='like',
            name='to_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='api.pet'),
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='pass',
            unique_together={('from_pet', 'to_pet')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('pet1', 'pet2')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('from_pet', 'to_pet')},
        ),
    ]
